# 使用 3.8 版本語法
version: '3.8'
# 定義所有要運行的服務 (services)
services:
  # 第一個服務：您的 Spring Boot 應用程式
  app:
    # build 指令會使用當前目錄的 Dockerfile 來建立 image
    # 如果您已經手動建立好名為 commerce.service 的 image，也可以替換成下面這行：
    # image: commerce.service
    build: .
    # 將主機的 8080 port 連接到容器的 8080 port
    ports:
      - "8080:8080"
    # 前面要大寫 SPRING_DATASOURCE:URL
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/commerce_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kermitpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    # 指定此服務依賴 db 服務，Compose 會確保 db 啟動後才啟動 app
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      # Compose 啟動時會自動建立名為 commerce_db 的資料庫
      MYSQL_DATABASE: commerce_db
    # 將資料庫資料持久化儲存，避免容器刪除後資料遺失
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: